name: Run CAISO Scraper Daily

on:
  schedule:
    - cron: "0 10 * * *"  # 6am ET (10 UTC)
  workflow_dispatch:  # Allow manual runs

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    env:
      GOOGLE_SHEETS_KEY_BASE64: ${{ secrets.GOOGLE_SHEETS_KEY_BASE64 }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run scraper
        run: python caiso_scraper.py
