name: Run CAISO Multiday Scraper

on:
  schedule:
    - cron: '0 22 * * *'  # Runs daily at 22:00 UTC (10PM UTC)
  workflow_dispatch:  # Allows manual runs from GitHub UI

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gspread pandas selenium oauth2client webdriver-manager

      - name: Run the scraper
        env:
          GOOGLE_SHEETS_KEY_BASE64: ${{ secrets.GOOGLE_SHEETS_KEY_BASE64 }}
        run: python CAISO_ESR_Multiday_Scrape.py
